import = [
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]
[shell]
program = "/bin/zsh"
[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold   = {family = "JetBrains Mono", style = "Bold"}
size = 18
[mouse]
hide_when_typing = true
[window]
opacity = 0.95
[keyboard]
bindings = [
{ key = "I", mods = "Alt", action = "IncreaseFontSize" },
{ key = "D", mods = "Alt", action = "DecreaseFontSize" },
{ key = "R", mods = "Alt", action = "ResetFontSize" }
]
