#! /bin/sh
sh ~/.config/polybar/launch.sh
feh --bg-fill Downloads/wallhaven-l38p3r.png
picom &
copyq &
fcitx5 &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI 

bspc config border_width         4
bspc config window_gap          15
bspc cpnfig normal_border_color \#7C42D0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome-stable desktop='^2'
bspc rule -a linuxqq state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
